Currency Converter, 1st iterration
itapaullus/CurrencyConverter pull request #1
Opened 2023-05-04 20:36 UTC by itapaullus

Нужно обсудить тесты, кажется они некорректно из под мавена запускаются у меня...

2023-05-05 15:07 UTC, kegisa requested changes

2023-05-05 15:07 UTC, kegisa commented on pom.xml
> +        <testSourceDirectory>src/test/java/implementations</testSourceDirectory>
давай пока без тестов

2023-05-05 15:07 UTC, kegisa commented on src/main/java/ConsoleCurrencyConverter.java
> +                System.out.print("Enter currency code to convert from: ");
Лучше логику вынести в какой то отдельный класс, иначе не получится заменять интерфейсы взаимодействия с клиентом.

2023-05-05 15:07 UTC, kegisa commented on src/main/java/ConsoleCurrencyConverter.java
> +                } catch (IllegalArgumentException e) {
Разве других исключений не может быть?

2023-05-05 15:07 UTC, kegisa commented on src/main/java/ConsoleCurrencyConverter.java
> +    public static void main(String[] args) throws IOException {
Почему мейн в этом же классе?

2023-05-05 15:07 UTC, kegisa commented on src/main/java/ConsoleCurrencyConverter.java
> +            {
что то уехало

2023-05-05 15:07 UTC, kegisa commented on src/main/java/implementations/JsonExchangeRateProvider.java
> +import org.json.*;
идею настрой на разворачивание всех импортов

2023-05-05 15:07 UTC, kegisa commented on src/main/java/implementations/JsonExchangeRateProvider.java
> +        byte[] jsonData = Files.readAllBytes(Paths.get(filename));
точнго нужно это каждый вызов метода делать?

2023-05-05 15:07 UTC, kegisa commented on src/main/java/implementations/SimpleCurrencyConverter.java
> +    private final Map<CurrencyPair, Double> rates;
врядли конвертер должен хранить в себе курсы валют, это неплохо бы вынести в класск который эти валюты получает

2023-05-05 15:07 UTC, kegisa commented on src/main/java/ConsoleCurrencyConverter.java
> +    public static void main(String[] args) throws IOException {
IOException тогда надо бы отловить

2023-05-05 15:07 UTC, kegisa commented on src/main/java/ConsoleCurrencyConverter.java
> +                System.out.print("Enter currency code to convert from: ");
а лучше где то на более низком уровне его заменить на свое исключение

2023-05-05 15:07 UTC, kegisa commented on src/main/java/model/CurrencyPair.java
> +    public String curFrom;
private

2023-05-05 15:07 UTC, kegisa commented on src/main/java/interfaces/CurrencyConverter.java
> +    double convert (String curFrom, String curTo, Double Amount) throws IOException;
конвертер должен выбрасывать исключение связанные с вводом и выводом?

2023-05-05 15:07 UTC, kegisa commented on src/main/java/ConsoleCurrencyConverter.java
> +                    double new_amount = converter.convert(curFrom, curTo, amount);
camelCase

2023-05-14 07:23 UTC, kegisa requested changes

2023-05-14 07:23 UTC, kegisa commented on src/main/java/ConverterApp.java
> +            ui.ShowMenu();
методы с малкнькой буквы пишутся

2023-05-14 07:23 UTC, kegisa commented on src/main/java/ConverterApp.java
> +            if (action.equals(Action.Quit)) {
enum в апперкейсе лучше писать

2023-05-14 07:23 UTC, kegisa commented on src/main/java/ConverterApp.java
> +                    System.out.println(converter.convert(
если изменим интерфейс взаимодействия ты все равно выведешь в консоль результат

2023-05-14 07:23 UTC, kegisa commented on src/main/java/converter/SimpleCurrencyConverter.java
> +    private final ExchangeRateProvider provider;
лишняя зависимость для конвертера, он может обойтись без этого, просто принимать на вход метода сразу валюту нужную и просто переводить, а  не вытаскивать данные

2023-05-14 07:23 UTC, kegisa commented on src/main/java/converter/SimpleCurrencyConverter.java
> +    public double convert(String curFrom, String curTo, Double amount) throws IllegalArgumentException{
врядли конвертер должен выбрасывать illegalargument он же просто считает, когда уберешь зависимость эти побочки тоже уйдут.

2023-05-14 07:23 UTC, kegisa commented on src/main/java/rateprovider/JsonExchangeRateProvider.java
> +    private CurrencyRateRepository rates;
вот это по моему лишнее, но в целом ОК

2023-05-16 19:14 UTC, itapaullus commented on src/main/java/ConverterApp.java
> +            if (action.equals(Action.Quit)) {
+

2023-05-17 05:12 UTC, kegisa requested changes

2023-05-17 05:12 UTC, kegisa commented on src/main/java/model/Currency.java
> +    private static final Map<String, Currency> currencyMap = new HashMap<>();
Зачем в enum логику добавлять?

2023-05-17 05:12 UTC, kegisa commented on src/main/java/rateprovider/JsonExchangeRateProvider.java
> +            this.rates = new InMemoryCurrencyRateRepository(exchangeRates);
хардкод реализации, я бы вообще эту прослойку убрал чтобы не путаться, сделай просто здесь мапу в этом классе, первый раз когда запросят валюту заполни эту мапуиз файла, далее бери из мапы, если вдруг в мапе не найдено надо снова сходить в файл перезаполнрить мапу и попрбовать найти, если ненайдено тогда исключение

2023-05-17 05:12 UTC, kegisa commented on src/main/java/ui/Action.java
> +    static {
я не понимаею зачем ты в enum этот код пишешь?

2023-05-17 08:57 UTC, merged